source 'https://rubygems.org'

gem 'acts-as-taggable-on', '~> 2.4.0'
gem 'activeadmin', github: 'gregbell/active_admin', branch: '0-6-stable'
gem 'active_skin'
gem 'acts_as_votable', '~> 0.10.0'
gem 'devise'
gem 'friendly_id', '~> 4.0.9'
gem 'griddler'
gem 'haml'
gem 'jquery-rails', '2.3.0'
gem 'kaminari'
gem 'meta_search',    '>= 1.1.0.pre'
gem 'mysql2'
gem 'paperclip'
gem 'progress_bar', git: 'git://github.com/fivedigit/progress_bar.git'
gem 'public_activity'
gem 'rack-mini-profiler'
gem 'rails','3.2.17'
gem 'rails3_acts_as_paranoid', '~>0.1.4'
gem 'rails3-jquery-autocomplete'
gem 'rails-timeago'
gem 'RedCloth'
gem 'resque', require: 'resque/server'
gem 'sass'
gem 'sass-rails', '~> 3.2.6'
gem 'sunspot_rails', '~> 1.3.3'
gem 'whenever', require:  false

group :development, :test do
  gem 'capybara'
  gem 'debugger'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'flog'
  gem 'haml-rails'
  gem 'hpricot'
  gem 'rails_best_practices'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'selenium'
  gem 'selenium-webdriver', '= 2.43.0'
  gem 'sextant'
  gem 'sunspot_solr', '~> 1.3.3'
  gem 'web-app-theme', git: 'git://github.com/pilu/web-app-theme.git'
  gem 'webrick', '~> 1.3.1'
end
group :assets do
  gem 'coffee-rails', '~> 3.2.2'
  gem 'font-awesome-rails'
  gem 'therubyracer', '~> 0.12.1'
  gem 'uglifier'
end

group :test do
  gem 'database_cleaner'
  gem 'sunspot_matchers'
  gem 'simplecov', '~> 0.7.1'
end
