source 'http://rubygems.org'

gem 'acts-as-taggable-on', '~> 3.0.0.rc1'
gem 'activeadmin', github: 'activeadmin'
gem 'active_skin'
gem 'acts_as_votable', '~> 0.10.0'
gem 'devise'
gem 'friendly_id'
gem 'griddler'
gem 'haml'
gem 'jquery-rails', '2.3.0'
gem 'kaminari'
gem 'mysql2'
gem 'paperclip'
gem 'progress_bar', git: 'git://github.com/fivedigit/progress_bar.git'
gem 'public_activity'
gem 'rack-mini-profiler'
gem 'rails', '4.1.8'
gem 'paranoia'
gem 'rails3-jquery-autocomplete'
gem 'rails-timeago'
gem 'RedCloth'
gem 'resque', require: 'resque/server'
gem 'sass'
gem 'sass-rails'
gem 'sunspot_rails'
gem 'whenever', require:  false

gem 'protected_attributes'
gem 'rails-observers'
gem 'actionpack-page_caching'
gem 'activerecord-deprecated_finders'
gem 'turbolinks'
# gem "strong_parameters"

group :development, :test do
  gem 'capybara'
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'flog'
  gem 'haml-rails'
  gem 'hpricot'
  gem 'rails_best_practices'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'selenium'
  gem 'selenium-webdriver', '= 2.43.0'
  gem 'sextant'
  gem 'sunspot_solr'
  gem 'web-app-theme'
  gem 'webrick', '~> 1.3.1'
end
group :assets do
  gem 'coffee-rails'
  gem 'font-awesome-rails'
  gem 'therubyracer', '~> 0.12.1'
  gem 'uglifier'
end

group :test do
  gem 'database_cleaner'
  gem 'sunspot_matchers'
  gem 'simplecov', '~> 0.7.1'
end
