source 'https://rubygems.org'

ruby '2.1.5'

gem 'acts-as-taggable-on', '~> 3.0.0.rc1'
gem 'activeadmin', git: 'https://github.com/gregbell/active_admin.git', ref: 'd11c0a5'
gem 'active_skin'
gem 'acts_as_votable', '~> 0.10.0'
gem 'devise'
gem 'friendly_id', '~> 5.0.4'
gem 'griddler'
gem 'haml'
gem 'jquery-rails', '~> 3.1.2'
gem 'jquery-ui-rails', '~> 4.2.1'
gem 'kaminari'
gem 'mysql2'
gem 'paperclip', '~> 4.1.1'
gem 'progress_bar', git: 'git://github.com/fivedigit/progress_bar.git'
gem 'public_activity'
gem 'rack-mini-profiler'
gem 'rails', '4.1.8'
gem 'paranoia', '~> 2.0.1'
gem 'rails3-jquery-autocomplete'
gem 'rails-timeago'
gem 'RedCloth'
gem 'resque', require: 'resque/server'
gem 'sass'
gem 'sass-rails', '~> 5.0.0'
gem 'sunspot_rails', '~> 2.1.1'
gem 'whenever', require:  false
gem 'coffee-rails', '~> 4.1.0'
gem 'font-awesome-rails'
gem 'therubyracer', '~> 0.12.1'
gem 'uglifier'
gem 'rails-observers'
gem 'actionpack-page_caching'
gem 'turbolinks'

group :development, :test do
  gem 'capybara'
  gem 'byebug', '~> 3.5.1'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'flog'
  gem 'haml-rails'
  gem 'hpricot'
  gem 'rails_best_practices'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'selenium'
  gem 'selenium-webdriver', '= 2.45.0'
  gem 'sextant'
  gem 'sunspot_solr', '~> 2.0.0'
  gem 'web-app-theme'
end

group :test do
  gem 'database_cleaner'
  gem 'sunspot_matchers'
  gem 'simplecov', '~> 0.7.1'
end
